gallantlab/pycortex

- cortex/quickflat.py
In merging Fatma's fix, I realized there was a reasonably easy way to add the kwargs from make_png to make_svg - namely, to use make_png to create the image layer in make_svg. This is perhaps not optimal, in that you might want to have curvature, data, dropout, etc all stored as separate image layers in the svg file, but it's much more functional than make_svg was before. It still maintains what I see as the main point of make_svg, which is to generate an image with vector graphic, editable ROI lines and labels on top of it.  
I'm going to leave this here in case anyone wants to test it out, and merge it in a few days.
> fix to make_svg to allow make_png kwargs to be used

- README.md
These can go faster if you add me as a collaborator... ;D
> Added some missing dependencies to the docs

- docs/conf.py
- docs/index.rst
- examples/README.txt
> added structure for sphinx_gallery

- docs/conf.py
better theme, already installed as dependency
> added table of contents to sidebar, switched to alabaster theme

- cortex/options.py
Can ya check me on this? @jamesgao
> options should check for webgl/colormap option, but instead check for basic/filestore twice

- examples/datasets/plot_vertexRGB.py
> DOC fixed an indexing with floats issue in plot_vertexRGB

- docs/database.rst
Starting to edit the documentation for the `pycortex` filestore/database
> docs: editing the filestore/database documentation

- cortex/defaults.cfg
- cortex/quickflat/composite.py
- cortex/quickflat/utils.py
- cortex/quickflat/view.py
- cortex/svgoverlay.py
- cortex/webgl/view.py
- examples/quickflat/plot_advanced_compositing.py
- examples/quickflat/plot_rois.py
- examples/quickflat/plot_sulci.py
- examples/quickstart/plot_retinotopy_flatmap.py
Fixing bugs in handling of config file defaults.
> Correct read of config defaults

- .travis.yml
- cortex/dataset/braindata.py
- cortex/defaults.cfg
- cortex/polyutils.py
- cortex/webgl/mixer.html
- cortex/webgl/resources/css/mriview.css
- cortex/webgl/resources/js/mriview.js
- cortex/webgl/resources/js/mriview_surface.js
- cortex/webgl/resources/js/shaderlib.js
- cortex/webgl/static.html
- cortex/webgl/view.py
- examples/surface_analyses/plot_flatmap_distortion.py
- examples/surface_analyses/plot_interpolate_data.py
- examples/surface_analyses/plot_tissots_indicatrix.py
Also updated contrast & brightness to work the same was as they do in quickflat.
> Config file defaults working for webgl

- cortex/xfm.py
Thank you @alexhuth for your comment! Following your suggestion, I've rewritten my scripts that imports / exports FreeSurfer transforms into python codes. Please check whether it works.
> Importing / exporting FreeSurfer transforms (i.e., register.dat files)

- cortex/webgl/serve.py
> check tornado version to avoid web viewer issues

- cortex/polyutils/__init__.py
- cortex/polyutils/misc.py
- cortex/polyutils/subsurface.py
- cortex/polyutils/surface.py
Minor updates to @sslivkoff 's subsurface code
> Subsurf updates

- cortex/__init__.py
- cortex/fmriprep.py
- examples/import_surface/import_fmriprep.py
I wrote a convenience function that can quickly import fmriprep data. Quite useful for my own work.
> Import fmriprep data

- cortex/align.py
- cortex/xfm.py
Made changes in cortex/align.py and xfm.py for doing manual alignment with freesurfer FreeView
> fsalign manual

- cortex/export/__init__.py
- cortex/export/panels.py
- cortex/export/save_views.py
> ENH add new view with inflated and lateral, medial, ventral views

- cortex/export/panels.py
- cortex/export/save_views.py
added kwargs
- `windowsize` to control size of the image to be saved
- `sleep` to control amount of time to wait for the viewer to load
also increase sleep time after image is saved
> ENH pass additional kwargs to plot_panels

- cortex/svgoverlay.py
- cortex/testing_utils.py
- cortex/utils.py
> FIX check inkscape version and modify cmd

- cortex/webgl/view.py
Makes animation functions work. Better, anyway.
> FIX: Updated animation functions in webgl.view to be more functional

- cortex/blender/blendlib.py
- cortex/segment.py
Turns out last PR did not work to create new .blend files, only worked if file was already extant. Oops. Added a feature as atonement for poor testing: new .blend files will have vertex colors displayed by default so you don't need to go hunting around in blender for how to display them.
> Tiny blender bug fix

- .github/workflows/build_docs.yml
- .github/workflows/run_tests.yml
Just testing this with this PR. I will merge after actions pass.
> MNT enable actions on PRs

- cortex/quickflat/utils.py
Without this change, `cortex.quickflat.make_svg` would fail because PIL required a C-contiguous array.
> FIX ensure c-ordering for flatmap image

- cortex/utils.py
Previously the code would fail because `gm_mapper` was undefined.
> FIX,DOC exception in get_roi_masks

- cortex/webgl/view.py
> MNT fix typos

- cortex/anat.py
- cortex/database.py
- cortex/dataset/braindata.py
- cortex/mayavi_aligner.py
- cortex/utils.py
- cortex/volume.py
- examples/utils/mni_to_subject.py
- examples/utils/plot_mosaic.py
- examples/utils/subject_to_mni.py
Worth looking into consequences of this a bit more before merge, perhaps; just a find and replace so far, but seems to work (with limited testing).
> MNT: updated get_data to get_fdata to support latest nibabel (5.0). 

- cortex/blender/__init__.py
- cortex/brainctm.py
- cortex/dataset/views.py
- cortex/mayavi_aligner.py
- cortex/utils.py
- cortex/webgl/view.py
- cortex/xfm.py
- examples/quickstart/plot_retinotopy_flatmap.py
- requirements.txt
Backward compatibility with python2.X is no longer necessary, six is now more trouble than it is worth.
> Removed dependency on 'six' library

- examples/quickstart/plot_retinotopy_flatmap.py
- examples/quickstart/retinotopy_webgl.py
This should solve the errors in building docs.
> FIX update URL of retinotopy dataset

- cortex/tests/test_dataset.py
- examples/utils/multi_panels_plots.py
> FIX np.product is deprecated in favor of np.prod

- cortex/tests/test_utils.py
- cortex/utils.py
Tests keep failing in another repo due to how temporary directories are handled. This is an attempt to fix it.
> ENH better handling of temp directory for downloading subjects

- cortex/quickflat/composite.py
- cortex/quickflat/view.py
Previously, had option to specify a subset of ROIs to show on flatmaps, but could not specify which sulci to show. This PR adds the ability to also specify a subset of sulci.
> ENH Add option to specify which sulci to show.
