cortex/mni.py
This is regarding the linear mni transformation.  There was a small bug in the transform_mni_to_subject method.
=> Get the data (volarray.get_data()) before creating a new nifti image.

README.md
Changing README to reflect the fact that pip is currently broken, adding instructions for installing from the git repo.
=> Docs update to reflect broken pip

cortex/webgl/simple.html, cortex/webgl/template.html, cortex/webgl/view.py
Currently, the HTML title of rendered output is hard-coded as `Brain`. This allows the `title` to be set via `kwargs` to `make_static`, with a default to `Brain`.
If accepted, this would allow, for example, NeuroVault to display the title of the image displayed to users (see https://github.com/NeuroVault/NeuroVault/issues/398)
=> ENH: allow HTML title to be set via make_static kwargs.

cortex/dataset/view2D.py
Very minor change: if you provide a keyword arg alpha=a to the Volume2D class, it now will over-ride any alpha channel created by the colormap you originally specified. If you provide no alpha, still functions as before (colormap sets alpha channel).
=> added alpha override to Volume2D

cortex/segment.py
added 'sname=cx_name' to the segment_cut function so import_flat knows what to work with. This fixes the error I was getting when trying to flatten a subject with differing freesurfer and pycortex names.
=> added 'sname=cx_name' to the segment_cut function 

cortex/brainctm.py, cortex/rois.py, cortex/utils.py
need to do this for travis auto generated docs to work. shouldn't break python2.7 if you have recent version of 2.7
=> docs: make print functions instead of print statements

cortex/mni.py, cortex/svgoverlay.py
Autogeneration of docs through Travis CI and `doctr` requires that all of the gallery code be compatible with python3. The goal of this PR is to bring python3 compatibility to just those parts of pycortex that the gallery code uses.
=> changes that make the gallery examples python3 compatible (for doc autogeneration with doctr/travis CI)

cortex/webgl/serve.py
Fixed bug in python3. When using the `setData` function to pass new data to a volume, python3 `json` package does some weird stuff and can't make sense of the volume data. A default flag for `json.dumps` is `ensure_ascii=True`, which makes everything bytes. Setting that to `false` and making encoding the data as `utf-8` fixes it. This suggested fix does not break the feature in python2.
=> give flag ensure_ascii=False to dumps when communicating with webgl

cortex/webgl/resources/js/shaderlib.js
Added 0.5 to the slice coordinate before mod() and floor() operations. This workaround avoids the problem caused by lower numerical accuracy on GPUs (e.g., non-textured stripes in the slice direction).
Original:
Fixed:
=> Fix for non-textured stripes in WebGL mode.

cortex/freesurfer.py, cortex/webgl/resources/js/mriview_surface.js, cortex/webgl/resources/js/shaderlib.js
**This branch is not complete yet, but I created the PR to facilitate discussion about these features and related changes.**
This adds volume-based cortical surface stratification to the webgl viewer. This changes the behavior of the 'depth' slider, so that for a selected depth (e.g. depth=0.5), the resulting surface is not halfway between the pial and white matter surfaces, but is instead a surface that has half of the cortical volume above it and half of the cortical volume below it. This obeys "Bok's principle", and much more accurately matches actual cortical layers than the current method.
In preliminary testing volume-based straficiation seems to have a modest effect on the mapping of high-resolution data, such as T1-weighted volumes, but I haven't tested lower resolution functional …
=> Volume-based stratification of the cortical surface

cortex/brainctm.py
There's a small bug when generating the overlay for example the example S1_retinotopy subject. The code naively assumes that all text elements in the SVG file contains the `data-ptidx` attribute. This is not the case. This PR adds an if-statement that fixes this.
=> fix saving overlays with text elements other than data-ptidx

cortex/options.py, setup.py
Handle config edge case properly (config dir exists but not the config file), make the tornado requirements consistently flexible to avoid needless downgrades when pip installing.
=> Incremental install / configuration tweaks

cortex/blender/__init__.py, cortex/brainctm.py, cortex/svgoverlay.py, cortex/utils.py, cortex/webgl/resources/js/mriview.js, cortex/webgl/resources/js/svgoverlay.js, cortex/webgl/resources/js/three.js, cortex/webgl/view.py
In constructing the viewer for my paper, I made a few updates to the javascript & other code. The biggest two changes are (1) to allow selection of a different dataset to activate a second javascript picker function (Alex did this in his viewer for his Nature paper before the dataset selection code existed in the webgl version of pycortex, so this was necessary), (2) to allow input of external SVG files for customized display layers in a webgl static viewer, and (3) to allow selection of which layers of an overlays svg file are ultimately available in the viewer. For example, one might want to get rid of the cutouts layer, which is used in quickflat but not so useful to include in a webgl display, or to select among a few options for fancy display layers in an external file.
There are a …
=> Picker updates

cortex/polyutils/subsurface.py
Fix error that occasionally occurs with patches that are actually two areas connected with a single edge but zero polys. Uses poly adjacency instead of vertex adjacency when getting connected vertices within a mask. Retains option to use the old version which is slightly faster, but is not default. The new version can probably be sped up slightly, but when working with 10mm patches, it is only about a 2~3ms difference.
=> Subsurf fix

cortex/anat.py, cortex/freesurfer.py
This code imports the whitematter segmentation from freesurfer instead of using the unreliable segmentation from fast. This should solve issue #284 .
=> use freesurfer segmentation for bbr

cortex/svgoverlay.py
These additions solve issue #288 "svg parser can't handle paths with h or v commands".
I ran into a problem with the handling of path commands when I attempted to make a ROI mask via `cortex.utils.get_roi_masks` as currently the code in svgoverlay.py lacks a way to handle h/v commands. I added code to both the `gen_path` function and the `_parse_svg_pts` function (used by the deprecated `get_roi_mask`) that registers the h/v command and handles the corresponding amount of movement specified in the path. In both functions, I handle h/v almost exactly the way the regular line (lowercase L) command is handled, and the new code just specifies whether the value following the command in the path is x or y movement and sets the other dx/dy value to 0.
I tested the code by plotting several ROIs …
=> Added code to parse paths with h or v commands

cortex/svgoverlay.py
I added four lines of code to improve the ability to parse paths in the overlays file. The previous recent update to this ( #311) failed to fully solve the problem with the h and v commands, it couldn't handle the upper case version of h and v. This should fully solve the problem (#288).
=> improve ability to parse path in overlays file

.gitignore, cortex/quickflat/composite.py, cortex/quickflat/utils.py, cortex/quickflat/view.py
This PR enables plotting a flatmap in a matplotlib Axes, so you can plot multiple flatmaps in the same Figure.
The changes are in 5b9c548681cc46056d02665824887aa54b5af55e.
The other commit 18971a446d7055165f8311b77eca1d052a696de4 is only removing unused imports and doing some pep8 alignments.
Example:
=> Enable passing an ax in quick flatmap: quickshow(fig=ax)

cortex/webgl/resources/js/movement.js
This PR affects the azimuth/altitude/target controls of the viewer i.e. the parameters changing the camera. We can change them with the mouse (clic and drag), the cursors, or indirectly while changing the `unfold` parameter (performing a smooth camera view interpolation).
From what I understand, the desired interpolation between the folded view and the flat view is performed [here](https://github.com/TomDLT/pycortex/blob/c7bcf2e6a0396899c9755b155932382ad64915b1/cortex/webgl/resources/js/movement.js#L125-L129).
However, the commented lines in this PR perform another (unwanted ?) interpolation during mouse control of the camera view. Commenting them fixes the weird mouse control issue when `unfold > 0.5`.
Lines were added in a8ebc87760225a4b2ba9798ce29a5ce5e4b.
I am willing to clean up …
=> Fix the mouse control weird behavior at unfold > 0.5

cortex/__init__.py
This error occurs every time `formats` doesn't import from `cortex`. There can be other reasons for this than the stated one, for example that `formats.pyx` wasn't compiled correctly.
=> FIX error message on import from source directory

cortex/__init__.py, cortex/export/__init__.py, cortex/export/export.py, cortex/export/panels.py, cortex/export/save_views.py, examples/utils/plot_multi_panels.py, setup.py
This PR adds two functions, `save_3d_views` and `plot_panels`, to create programmatically figures with multiple views of the same volume. It proposes two layouts as examples.
I added this in a new module, poorly named `export`. Feel free to suggest a better name.
=> ENH add save_3d_views and plot_panels functions

cortex/__init__.py, cortex/utils.py, requirements.txt
Per discussion around fsaverage, added function to download a subject. For now, I've put the fsaverage subject on figshare, but that is open to discussion. Also, this provides a general mechanism for easily adding subjects that other people have stored at arbitrary web locations.
=> ENH: added function to download new subjects for pycortex from web URLs

cortex/fmriprep.py
Heya,
There was an issue with fmriprep data with fmriprep >1.2.0, since [they changed the names of the output files](https://fmriprep.readthedocs.io/en/stable/changes.html#october-31-2018). This branch can now deal with that.
Furthermore, I ran into the same issue as @anwarnunez in issue https://github.com/gallantlab/pycortex/issues/304. I guess you want your subject names to depend on the dataset you're using. I made a little argument for that as well.
=> Added fmriprep import functionality

cortex/quickflat/composite.py, cortex/quickflat/utils.py, cortex/quickflat/view.py, examples/quickflat/plot_thickness_nanmean.py
This adds the kwarg `nanmean` to `cortex.quickshow`. Setting `nanmean` to True makes quickflat only take the mean over non-nan values when averaging across the thickness of cortex. Pixels will still be set to nan if every voxel across the thickness is nan.
By default `nanmean` is set to False, giving the current behavior (i.e. no existing plots should change after this merge).
I also created an example that shows how it works.
This might solve issues #323 and #280.
=> Thickness nanmean

cortex/quickflat/utils.py, cortex/svgoverlay.py, examples/quickflat/plot_advanced_compositing.py, examples/quickflat/plot_rois.py
This PR fixes the possibility to change the display of ROI labels.
It also demonstrates such changes in an example.
=> FIX ROI label display parameters

README.md, docs/install.rst
This PR relates to #358 - and acts to standardize the listed instructions to install and run the demo, updating from having two different versions between the README and documentation site.
This basically updates the documentation site to follow what was in the README. Following this approach, I tested I can install and run the demo. It needs checking to make sure this is the right approach to recommend to users, and check I haven't missed anything.  
Notes on the updates:
- I dropped reference to using either anaconda or venv
- This follows the discussion in #358, and is based on the idea that it can / should be up to the user as to how manage an environment for pycortex
- I consolidated the docsite so the install and demo instructions to follow what was in the README
- For install, this …
=> Update and consolidate install & demo instructions

cortex/__init__.py, cortex/dataset/__init__.py, cortex/dataset/viewRGB.py, cortex/dataset/views.py, cortex/quickflat/view.py, cortex/utils.py, examples/datasets/plot_volumeRGB.py, requirements.txt
Added things to `VolumeRGB` to allow data channels to be mapped to custom base colors instead of just red, green, and blue. Also added an option to have all three data channels to use the same `vmin` and `vmax`. Backwards compatible as the default behavior is to bypass all the new features and map data channels directly to RGB.
Also added a `Colors` class to keep track of colors to use.
Specify custom colors:
`volume = cortex.VolumeRGB(visual, progression, integration, subject, transform, channel1color = cortex.Colors.RoseRed, channel2color = cortex.Colors.LimeGreen, channel3color = 
cortex.Colors.DodgerBlue)`
Force shared ranges:
`volume = cortex.VolumeRGB(visual, progression, integration, subject, transform, shared_range = True)`
Also have a minor thing to specify an overlays file in …
=> Custom colors in VolumeRGB

pyproject.toml
This additionl made it possible to install the software with pip. It's a change that is compliant with https://www.python.org/dev/peps/pep-0518/ as I understand it. This PR is created thanks to the experience of @arokem that demonstrated this to resolve issues for other packages with similar build dependencies.
Previously, users of the software might have encountered situations like that described here: pypa/pip#5761. This fix should resolve that with modern versions of pip.
=> Add pyproject.toml for modern pip installs

.travis.yml, README.md, setup.py
Travis is failing (e.g. in #384) on python 3.7+ due to a backward incompatibility in numpy ABI in version 1.20 ([see explaination](https://github.com/scikit-learn-contrib/hdbscan/issues/457)), and because pip is mixing the versions during the install.
This should fix the failure.
=> FIX pycortex install with numpy < 1.20

cortex/align.py
Freesurfer's BBR registration works much better, so let's switch to that default. Also, initializing with `mri_coreg` is more robust than using FSL.
=> ENH Use freesurfer BBR by default for automatic alignment with mri_coreg

cortex/dataset/dataset.py, cortex/svgoverlay.py, cortex/tests/test_dataset.py
Running the tests always creates/modifies some files, that one has to delete/revert before doing a git commit. This is a bit annoying. This PR avoid creating a useless `rois` file, and avoid modifying `filestore/db/S1/overlays.svg`.
On the way, this PR also:
- fixes `test_pack` which was partly commented out because it was broken.
- add an option to preserve svg files when loading them with `cortex.db.get_overlay`
=> TST clean up and fix `test_dataset.py::test_pack`

cortex/svgoverlay.py
See #390.
There is another place where `INKSCAPE_VERSION` is used (`cortex.utils.add_roi`), but that requires the user to pass an `open_inkscape` kwarg, so I think we can skip the check there.
=> FIX add more informative error in get_texture if inkscape is not installed

cortex/webgl/serve.py
Use base64.encodestring if python version < 3.0, otherwise use
base.encodebytes.
base64.encodestring is deprecated (unavailable in python3.9), and
base64.encodebytes is unavailable in python2.
https://docs.python.org/3.1/library/base64.html#base64.encodebytes
=> DEP Use encodebytes instead of encodestring.

cortex/blender/__init__.py, cortex/blender/blendlib.py, cortex/segment.py
approximately working, needs further testing. 
One big annoyance with blender 2.8 is that if you open a .blend file with blender 2.8+, you will no longer be able to open it with blender 2.7. Nuking backward compatibility seems bad, so what I have tried to do here is implement an automatic (and likely annoying) backup:  every time you try to call a command that opens blender on an extant file, it creates a backup (<file>_b2.7bkup.blend). This happens once for the file (presumably, the first time it is called with the updated code if the blender version is >= 2.8). 
Putting a flag around these backups is potentially a good idea - something settable in the config file? e.g. make_legacy_backups=True, then once people decide they don't want a million _b2.7bkup files running around, and that …
=> ENH: Long-overdue update to Blender 2.8+

cortex/defaults.cfg, cortex/webgl/view.py
This PR makes it easier for me to view webgl viewers on my lab machines, which have extra domain info (blah.unr.edu) which isn't present by default in the webgl server address that pops up in pycortex. The upshot of this is that without this PR I need to change the address that pops up in order to see the webgl viewer, every time. This is annoying. Should be no change for anyone else, fully backward compatible. There may be a way to do this with `socket` or some other means, but `socket.getfqdn()` did not work for me, and my googling wasn't able to turn up anything else.
=> ENH: added config file specfication of domain name; blank by default

cortex/database.py, cortex/tests/test_utils.py, cortex/utils.py
The function `cortex.utils.download_subject` does not update the database (`cortex.db`) with the newly added subject, because the cached dictionary is not updated `cortex.db._subjects`. This PR reset the cached dictionary to update the list of available subject after the download.
This PR also changes the default filestore to the current filestore in use (`cortex.db.filstore`) instead of the one listed in the config file.
=> FIX add downloaded subjects to the cortex database

cortex/options.py
Right now the installation step assumes that `~/.config` exists. The installation blows up if the directory doesn't exist (see #414). Creating intermediate dirs should be a simple enough fix for the problem.
=> FIX create intermediate dirs for config file

.github/workflows/build_docs.yml, .github/workflows/run_tests.yml
Sometimes sources might be unavailable and cause the actions to fail (see #417)
=> FIX update sources before apt-get installing

cortex/align.py
This option is useful to improve automatic alignment of a partial field of view image using a whole field of view intermediate image.
=> ENH add option for intermediate image in bbregister

cortex/webgl/resources/js/mriview_surface.js
When the sampler is changed (nearest or trilinear) in the viewer, it only affects the current dataview. After changing the dataview, the menu still displays the new value, but the sampler actually uses the old value.
Example:
- view A, the menu displays "nearest", the view uses "nearest"
- (click on "trilinear" in the menu)
- view A, the menu displays "trilinear", the view uses "trilinear"
- (click on view B)
- view B, the menu displays "trilinear", the view uses "nearest"
This PR fixes this bug. The behavior is now consistent with the other sampling options, that persist when changing the dataview.
=> FIX keep current sampler when dataview changes

cortex/webgl/resources/js/mriview_surface.js
With the change in #420, the viewers hang with "loading brain". I tested this on two different machines and two different operating systems (but with the same browser: firefox). Removing that line fixes the problem. I don't know enough javascript to figure out if there's a better fix...
This reverts commit d388b2b2cf47a2e3acc38a2567a85495d262e443.
=> Revert "FIX keep current sampler when dataview changes (#420)"

cortex/webgl/resources/js/dataset.js, cortex/webgl/resources/js/mriview_surface.js
This is a second attempt to fix the issue described in #420 (which was reverted in #421).
=> FIX keep current sampler when dataview changes - v2

cortex/export/save_views.py
`cortex.export.save_views` would fail previously if a vertex object was passed instead of an object.
This PR also adds two additional default lateral views that are slightly rotated to view frontal and temporal cortices (`left_atl`, `right_atl`).
=> FIX set interpolation and layers only for volumes

cortex/dataset/braindata.py, cortex/dataset/view2D.py, cortex/dataset/viewRGB.py, cortex/tests/test_dataset.py
Vertex objects cannot use transparency as Volume objects because they are implemented differently in the viewer.
This PR adds a method to Vertex, Vertex2D, and VertexRGB, to mimic the transparency of Volume objects. The method blends the Vertex data with a curvature map, depending on a transparency (alpha) map, and returns a VertexRGB object.
It is a workaround for #323 and #387, using the method described in https://github.com/gallantlab/pycortex/issues/323#issuecomment-477463304.
=> ENH add blend_curvature method to Vertex, Vertex2D, and VertexRGB

cortex/quickflat/utils.py, cortex/quickflat/view.py
This PR adds the option to visualize areas of dropout also for `make_svg`. In addition, this PR fixes transparency issues with `make_svg`. (While `nan`s pixels are shown as transparent with `imshow`, they are not transparent when saved with `imsave`, so their alpha value needs to be modified accordingly.)
=> ENH,FIX add dropout option to make_svg, fix transparency

cortex/svgoverlay.py
The visibility setting of individual shapes in the `overlays.svg` file is currently not checked in `cortex.svgoverlay.get_texture`. This causes labels for invisible ROIs to show up in the quickflat. This PR fixes the logic by honoring the visibility of the SVG shapes in `overlays.svg`.
Previous version (note labels like FC, VTC, STG showing up):
This PR:
=> FIX do not show labels for invisible shapes

cortex/blender/blendlib.py
The `MeshColorLoop` object uses 3-dimensional rgb colors in [blender 2.79](https://docs.blender.org/api/2.79/bpy.types.MeshLoopColor.html), but uses 4-dimensional rgba colors in [blender 3.0.1](https://docs.blender.org/api/2.80/bpy.types.MeshLoopColor.html?highlight=meshloopcolor).
This PR updates `add_vcolor` to deal with this change: the blender version is detected, and the corresponding color format is used.
=> MAINT Deal with rgb vs rgba for different blender versions.

cortex/freesurfer.py
When a new flattened surface is imported into pycortex, the `overlays.svg` of the subject is removed from pycortex store. However, this produces an error if the subject does not yet have an `overlays.svg` file. This PR checks if the `overlays.svg` file exits, and only attempts to delete the file if it already exists.
=> FIX Check if overlays file exists before unlinking.

setup.py
Fixes #335, #360
In some machines (macos, colab), the install would put the filestore in a location of the form `build/bdist.*/wheel/pycortex-*.data/data/share/pycortex/db`, which seems to be deleted after the install. This PR fixes this issue by changing the default location.
___
Tested on my machine:
- before: `.../tomdlt/miniconda3/envs/py37/share/pycortex/db`
- after: `.../tomdlt/miniconda3/envs/py37/share/pycortex/db`
Tested on my machine, installing with `--user`:
- before: `.../tomdlt/.local/share/pycortex/db`
- after: `.../tomdlt/.local/share/pycortex/db`
Tested on Colab:
- before: `build/bdist.linux-x86_64/wheel/pycortex-1.2.3.data/data/share/pycortex/db`
- after: `/usr/share/pycortex/db`
=> FIX change location of filestore during the install

cortex/align.py
with deprecation warnings and legacy function fs_manual() that now just maps to manual()
=> Changed name of cortex.align.fs_manual to cortex.align.manual

cortex/quickflat/utils.py, cortex/tests/test_quickflat.py
When averaging over voxels to produce a flatmap, NaNs can be ignored using `nanmean=True`.
However, if the data is masked (e.g. with a "thin" mask), masked voxels are not ignored like NaNs.
Example with data filled with 1s and NaNs:
"thick" mask: correct behavior, averaging 1s into 1s, and NaNs into NaNs.
"thin" mask: incorrect behavior, averaging 1s into value in [0, 1].
The fix is to use `masked_data.filled()`, which fills masked numpy arrays with the value in `fill_vallue`.
<details>
```python
import cortex
import numpy as np
from matplotlib import pyplot as plt
subject = 'S1'
transform = 'fullhead'
for type_ in ["thin", "thick"]:
mask = cortex.db.get_mask(subject, transform, type=type_)
vol = cortex.Volume(np.ones(mask.sum()), subject, transform, cmap="viridis", vmin=0, vmax=1) …
```
=> FIX ignore masked voxels when averaging with nanmean=True

cortex/export/save_views.py
It looks like there was a small bug in how `save_3d_views` handled custom parameter dicts — it assumed that `view` was a string that could be used in the filename, but for custom parameter dicts it actually contained the dictionary of parameters. I separated the view name from the parameters dict and made the documentation more explicit.
=> FIX: fixed bug in save_3d_views handling custom parameter dicts

cortex/xfm.py
A simple fix for all these issues is to just take the last for lines, as @jwparks suggested.
While I was there, I also refactored the code to make it a bit more modular by extracting the function to call vox2ras-tkr.
This was manually tested by running `cortex.align.automatic`. Unfortunately, the test cannot be easily added to our unit tests because we would need freesurfer. (This makes me sad.)
Closes #441
=> FIX,REF Handle different header length for vox2ras tk

cortex/defaults.cfg
`fsl_prefix` is needed to be specified only if FSL is installed with NeuroDebian (and users do not want to source it with `/etc/fsl/fsl.sh` every time). However, FSL is stuck to 5.0 in NeuroDebian, and most people would install FSL with other means (e.g. the python FSL installer). So I think we should set the prefix to blank by default (see #443).
This PR also changes the default 2D colormap from RdBu_covar to PU_BuOr_covar, which I believe is a better default.
=> MNT change default fsl-prefix and 2D colormap

cortex/webgl/resources/js/axes3d.js
I realized that after calling `getImage`, sometimes the view was not rendered. I believe this is what caused the random crashes with `save_3d_views`. Forcing the view to be drawn again after `getImage` solves the random crashes. (Or at least, I've been running `cortex.export.plot_panels` for ~20 times in a loop and it hasn't crashed...
=> FIX random crashes in `save_3d_views`

cortex/export/_default_params.py, cortex/export/panels.py
Example output:
Code to generate example:
```python
import cortex
import numpy as np
from cortex.export.panels import params_flatmap_inflated_lateral_medial_ventral as params
subject = 'S1'
shape = cortex.db.get_xfm(subject, 'identity').shape
data = np.arange(np.product(shape)).reshape(shape)
volume = cortex.Volume(data, subject=subject, xfmname='identity')
cortex.export.plot_panels(volume, **params, save_name="example-new-view.png")
```
=> NF new params for a multipanel figure with all views

README.md
The current badge is outdated since we don't use Travis anymore.
=> MNT update CI badge to github actions

cortex/dataset/viewRGB.py
When creating a new `VertexRGB` object with vertices containing NaNs, the values of those vertices would be cast to uint8 and transformed to 0. However, the alpha value would be set to 1, causing the Nan vertices to appear black. This PR fixes this issue by automatically setting a correct alpha of 0 for NaN values. It partially addresses #455.
Minimal example:
```python
import cortex
import numpy as np
import matplotlib.pyplot as plt
roi = cortex.get_roi_verts("fsaverage", roi="IPS0")["IPS0"]
c = np.linspace(0, 1, 327684)
rgb = np.array([c, np.zeros_like(c), np.zeros_like(c)])
rgb[:, roi] = np.nan
vtx = cortex.VertexRGB(*rgb, "fsaverage")
cortex.webgl.show(vtx)
cortex.quickshow(vtx, with_colorbar=False, with_curvature=True);plt.show()
```
Before:
After:
=> FIX Correctly handle NaNs in `VertexRGB` and `VolumeRGB`

cortex/export/__init__.py
=> FIX add missing params to cortex.export.__init__

cortex/dataset/viewRGB.py
This should lead to a more intuitive behavior when passing an array as alpha to both `VolumeRGB` and `VertexRGB` objects.
=> FIX force vmin/vmax to 0/1 whenever an array is passed as alpha

cortex/dataset/viewRGB.py, cortex/dataset/views.py, cortex/quickflat/composite.py, cortex/quickflat/utils.py, cortex/tests/test_dataset.py
Pycortex raises an error with matplotlib 3.6, when it tries to register the same colormap twice. This is because the check `if self.cmap not in cm.__dict__` does not work anymore. (See recent changes to the colormaps API in matplotlib [here](https://matplotlib.org/3.6.0/api/prev_api_changes/api_changes_3.6.0.html#pending-deprecation-top-level-cmap-registration-and-access-functions-in-mpl-cm))
This PR:
- fixes how to check that the colormap is already registered
- refactors duplicated code into a new method `get_cmapdict` in `Dataview` and `DataviewRGB`
- add a test for clarity
I tested the fix with matplotlib 3.3 and 3.6.
=> FIX avoid registering the same colormap twice to matplotlib

cortex/dataset/viewRGB.py
Volume2D and Vertex2D objects use VolumeRGB/VertexRGB for plotting. They set the alpha channel to a uint8 array. This returns a warning, because the check on the alpha values is too liberal. This PR fixes the issue, and should warn only when the alpha array is a float.
=> MNT warn about alpha only if dtype is not uint8

cortex/dataset/view2D.py, cortex/tests/test_dataset.py
Add a warning for non-perceptually uniform 2D colormaps (first row in the plot) that have a clear perceptually uniform equivalent (second row in the plot). 
<details>
```py
import os
import cortex
cmapdir = cortex.options.config.get("webgl", "colormaps")
#######################
cmap_list = sorted(os.listdir(cmapdir))
fig, axes = plt.subplots(4, 8, figsize=(18, 10))
axes = axes.ravel()
for ax in axes:
ax.set_axis_off()
ii = 0
for cmap_file in cmap_list:
cmap_img = plt.imread(os.path.join(cmapdir, cmap_file))
if 1 not in cmap_img.shape:
axes[ii].imshow(cmap_img)
axes[ii].set_title(cmap_file)
ii += 1
fig.tight_layout()
plt.show()
######################################################################
mapping = {
"BuOr_2D":"PU_BuOr_covar",
"BuWtRd_alpha":"RdBu_r_alpha",
"RdBu_covar": …
```
=> ENH warn non-perceptually-uniform 2D colormap

.github/workflows/run_tests.yml, cortex/formats.pyx, cortex/tests/test_dataset.py, cortex/tests/test_formats.py, cortex/tests/test_polyutils.py
Fixes the most urgent issues with deprecation errors in nibabel.
We still need to change the `nibabel.get_data` to `nibabel.get_fdata`. Those will fail in Nibabel 5.0.X
=> MNT deal with some nibabel deprecation errors

README.md, docs/install.rst
It looks like the unencrypted git:// protocol was deprecated: https://github.blog/2021-09-01-improving-git-protocol-security-github/
When trying to install pycortex with `pip install -U git+git://github.com/gallantlab/pycortex.git`, it tries to clone from `git://github.com/gallantlab/pycortex.git`, which hangs. If we do `pip install -U git+https://github.com/gallantlab/pycortex.git`, it is able to successfully clone from `https://github.com/gallantlab/pycortex.git`.
=> FIX git URL for pip install

cortex/export/save_views.py
If a subject doesn't have a flatmap, then the unfold parameter needs to be 1 in order to get a fully inflated surface.
=> FIX `cortex.export.plot_panels` correctly shows inflated surfaces for subjects without a flatmap 

cortex/database.py, cortex/freesurfer.py, cortex/polyutils/subsurface.py, cortex/quickflat/composite.py, cortex/surfinfo.py, cortex/svgoverlay.py, cortex/utils.py, cortex/webgl/serve.py, cortex/webgl/view.py, cortex/xfm.py
Fixes #478
Numpy 1.24 has [expired](https://numpy.org/doc/stable/release/1.24.0-notes.html#expired-deprecations) some deprecation warnings and now raises errors. Here are the fixes for pycortex:
- Changes `np.int` into `int`, and `np.float` into `float` (dtype) or `np.float_` (casting function).
- Use explicitly `np.array(..., dtype="object")` to allow arrays of arrays of different lengths.
=> FIX stop using expired deprecation for numpy 1.24

.github/workflows/build_docs.yml, .github/workflows/install_from_wheel.yml, .github/workflows/run_tests.yml, cortex/quickflat/utils.py, cortex/tests/test_formats.py, pyproject.toml, requirements.txt
Cython 3.0 was released a couple of days ago, and it introduces changes that break our install process. For now we can just fix the issue by requiring cython < 3.0. In the long run, we may want to adapt our cythonized code.
Closes #490
=> MNT require cython<3.0 to avoid breaking install

examples/surface_analyses/plot_geodesic_path.py
Path was not visible in render due to averaging; this fixes that and makes a couple small changes.
=> EXA make path visible in fix_geodesic_path example

cortex/webgl/view.py
Now the curvature brightness/smoothness/contrast can be changed programmatically when starting `cortex.webgl.show`. This will allow changing these curvature values when using `cortex.export.plot_panels`.
(The PR also includes some sorting of the imports done automatically by isort...it doesn't hurt cleaning up the imports a bit.)
=> ENH allow setting curvature values when starting webgl viewer

cortex/freesurfer.py
New versions of nibabel will raise an error if the data has not the correct dtype.
=> FIX ensure correct datatype for mri_surf2surf

cortex/svgoverlay.py, cortex/webgl/resources/js/svgoverlay.js
I'm having some issues with loading some very old overlay files. Without the fix in the javascript part, the viewer does not even load. The fix in `svgoverlay.py` is still a work in progress. It fails creating splines for paths such as the following
```
M 612.125 549.625 C 606.51441 549.71551 601.02784 550.65202 596.09375 553 C 589.17538 556.29224 581.97592 562.54109 580.6875 570.09375 C 579.79889 575.30273 580.38513 580.34214 581.84375 585.28125 C 595.21597 595.86604 617.82389 619.97107 616.0625 634.59375 C 615.59786 638.45112 613.76677 641.15406 611.125 643.1875 C 611.24105 643.44807 611.35059 643.70914 611.46875 643.96875 C 614.40667 650.42362 617.18423 652.68087 618.625 659.625 C 619.66885 664.65608 614.83353 672.68837 618.625 676.15625 C 624.39758 681.43616 633.04748 677.01176 638.75 …
```
=> FIX check if shapes exist before setting the labels in the WebGL viewer

cortex/webgl/view.py
Whenever more than 10 volumes are passed to `cortex.webgl.show` or `make_static`, the viewer would crash because of the default `layout`. This PR removes the default and lets the user decide what layout to use explicitly.
=> FIX do not use a default layout selection for multiple volumes

cortex/utils.py
When loading an ROI mask or a set of vertices within an ROI, the code previously returned only vertices on the flatmap. This is fine in general, but if the ROI spans a cut, then those vertices won't be included and the ROI mask will ignore some voxels.
This PR fixes this issue by including the neighboring vertices that are not present in the flatmap.
**Before**
**After**
**Before**
**After**
=> FIX Improve masks returned by `get_roi_masks` and correctly split into left/right hemispheres

.github/workflows/codespell.yml, cortex/blender/__init__.py, cortex/database.py, cortex/dataset/viewRGB.py, cortex/freesurfer.py, cortex/mapper/samplers.py, cortex/mapper/volume.py, cortex/polyutils/subsurface.py, cortex/polyutils/surface.py, cortex/quickflat/view.py, cortex/segment.py, cortex/utils.py, cortex/version.py, cortex/webgl/view.py, cortex/xfm.py, docs/align.rst, docs/conf.py, docs/database.rst, docs/transforms.rst, docs/userguide/webgl.rst, examples/datasets/plot_vertex2D.py, examples/utils/multi_panels_plots.py, examples/utils/plot_roi_voxel_mask.py, pyproject.toml
=> Add codespell: workflow, config and fix typos it finds

cortex/freesurfer.py, examples/fsaverage/README.txt, examples/fsaverage/upsample_to_fsaverage.py
The example unfortunately cannot run on github actions, because we don't have a freesurfer installation. But I tested it locally, and it works.
=> ENH,EXA add function to upsample from fsaverageX to fsaverage

cortex/align.py
This change will allow using volumes with T1 contrast as a reference for automatic alignment. It will also allow passing a registration file for initialization.
I moved the code for the automatic alignment using FSL to `cortex.align.automatic_fsl`. I doubt it will be used because freesurfer's bbregister works very well, but it's there.
=> ENH Add more options for freesurfer's automatic alignment, move code for FSL's automatic alignment

cortex/utils.py
A small fix to `cortex.utils.add_cmap` to ensure that a proper filename is used when saving a new colormap. Also improve the docstring a bit.
=> FIX,DOC make sure cmap filename ends with png

cortex/database.py
Maybe this problem was a problem only for me. But I always hated how the transforms were listed in the `__repr__`, as it wasn't really easy to understand what transforms were available for a subject.
Before the PR they would be listed as
```
>>> cortex.db.subjects["fsaverage"].transforms
Transforms: [atlas,atlas336,atlas_2mm,atlas_3mm]
```
which is fine for a few transforms, but it becomes quickly unreadable if one has many transforms.
After this PR they are listed as
```
>>> cortex.db.subjects["fsaverage"].transforms
Available transforms for fsaverage:
atlas
atlas336
atlas_2mm
atlas_3mm
```
This PR also sorts the subjects when running `cortex.db` and `cortex.db.subjects`. The unsorted subjects also bugged me in the past.
=> ENH sort subject list and improve repr of transforms

cortex/freesurfer.py
This PR fixes the bug first described in #300. Pycortex always assumed that the surfaces were generated out of T1s with 1mm3 isotropic voxel size. If one imported surfaces generated from other volumes (e.g., sub-mm), then the surfaces would be misaligned (see example in #300). To fix this issue, here I'm simply importing and converting the surfaces to gifti with Freesurfer's `mris_convert --to-scanner`, which uses the same coordinate system as the T1 rather than the TKR system used for surfaces. 
This change produces the same surfaces as the old code for 1mm3 volumes. I'm waiting for freesurfer to finish on a sub-mm volume to test it there too.
(This PR also cleans up the code in that function a bit to make it easier to maintain...)
=> FIX,MNT import surfaces generated from volumes with any voxel size

cortex/dataset/braindata.py
The regex in `_find_mask` only allowed word characters in the name, so a mask name such as `mask_v1+v2+v3.nii.gz` would not be recognized.
This PR makes the regex more general. However, there's an argument to be made whether we should allow "+" in mask filenames. If we don't want, then we should enforce proper filenames in `cortex.db.save_mask`.
=> FIX allow any character in mask name

cortex/mapper/__init__.py, cortex/mapper/utils.py
These new functions can be used to project data from the volume to any arbitrary surface via a combination of pycortex mappers and `mri_surf2surf`. The projection deals with nans similar to quickshow and `nanproject=True`.
Example code:
```python
import cortex
from cortex.mapper import vol2surf
import numpy as np
subject = ...  # anonymized
xfm = ...  # anonymized
vol = cortex.Volume.random(subject, xfm, mask="thick")
mask = cortex.db.get_mask(subject, xfm)
data = vol.data[mask]
data[np.random.randn(*data.shape) > 0] = np.nan
new_volume = cortex.Volume(data, subject, xfm, mask="thick")
surface = cortex.Vertex(vol2surf(data, subject, xfm), subject)
fsaverage = cortex.Vertex(vol2surf(data, subject, xfm, target_surface="fsaverage"), "fsaverage")
fig = cortex.quickshow(new_volume, …
```
=> NF Add functions to project volume data to surface while dealing with NaNs.

cortex/utils.py, requirements.txt
=> FIX avoid using wget and use urllib

cortex/webgl/data.py, cortex/webgl/resources/js/datamodel.js
This was a nasty 🪲. To visualize a Vertex/VertexRGB object in a static viewer, the `NParray.fromURL` method in `datamodel.js` was using jQuery to fetch the numpy array with the data. However, jQuery by default serializes any type of data and so the binary buffer was automatically encoded as a string. This automatic serialization caused issues when a float32 array was saved (see below for an example.)
This PR completely rewrites the `NParray.fromURL` method to use an `XMLHttpRequest` instead of jQuery. In this way the buffer can be fetched as an arraybuffer, and all the portions of the buffer (header/data) can be decoded appropriately.
```python
import cortex
vtx = cortex.Vertex.random("fsaverage")
cortex.webgl.make_static(
outpath="test-viewer",
data=vtx,
recache=True,
)
```
```bash …
```
=> FIX avoid using jQuery for getting numpy arrays

cortex/webgl/view.py
This PR
- reorganizes the order of the kwargs for both `cortex.webgl.view.show` and `cortex.webgl.view.make_static` so that they match the docstring
- improves the docstring for both functions
- allows passing `curvature_{brightness,contrast,curvature}` to `make_static` too
- adds a new keyword `surface_specularity` in both functions to allow disabling that hideous surface specularity 😝 
- removes the `cmap` kwarg since it doesn't do anything anymore
=> NF,DOC improve docstring for show and make_static

cortex/webgl/resources/js/datamodel.js, cortex/webgl/resources/js/facepick.js, cortex/webgl/resources/js/mriview.js
This PR adds the feature of visualizing the VertexData value when hovering on the surface or when clicking on a specific vertex.
Example code to test that it works as intended (unfortunately it's hard to automate):
```python
import cortex
roi = cortex.get_roi_verts("S1", roi=["EBA"], mask=True)["EBA"]
roi = roi.astype(float)
vtx = cortex.Vertex(roi, "S1")
cortex.webgl.show(vtx)
```
Example images
=> NF display values at vertex in webgl viewer

.github/workflows/install_from_wheel.yml, .github/workflows/run_tests.yml, cortex/svgoverlay.py, cortex/utils.py, pyproject.toml, requirements.txt, setup.py
This should remove any explicit mentions of `distutils` and fix installation in Python 3.12.
I'm not super familiar with the packaging system, so there's 2 things I'm not sure about:
* Does anything else need to be done to address #538 ?
* Does setuptools still need to be pinned to `<60.0` ? It looks like this was done to fix #552, but the [NumPy migration docs](https://numpy.org/doc/stable/reference/distutils_status_migration.html#interaction-of-numpy-distutils-with-setuptools) suggest this is only if you're using `numpy.distutils` (which this PR removes).
=> MNT Remove dependency on distutils

.github/workflows/build_docs.yml, .github/workflows/install_from_wheel.yml, .github/workflows/run_tests.yml, cortex/blender/__init__.py, cortex/blender/blendlib.py, cortex/openctm.pyx, pyproject.toml, requirements.txt, setup.py
It managed to compile on Python 3.12 and 3.13 and run through the tests, but I haven't checked if the webviewer still works yet.
This should fix #563 .
=> Python 3.13 compatibility, and upgrade to Cython 3
